In [1]:
import json
from oltk.dataset.canvas_dataset import CanvasDataset

In [4]:
import polars as pl
pl.Config.set_fmt_str_lengths(256)
pl.Config.set_tbl_rows(32)

polars.config.Config

In [5]:
ds = CanvasDataset(root="./data/TestObscureVault", path="./data/TestObscureVault/Test.canvas")

In [6]:
ds.edges

shape: (22, 7)
┌─────┬─────────┬───────────┬───────┬─────────┬─────────────────┬──────────────────────────┐
│ id  ┆ from_id ┆ from_side ┆ to_id ┆ to_side ┆ type            ┆ label                    │
│ --- ┆ ---     ┆ ---       ┆ ---   ┆ ---     ┆ ---             ┆ ---                      │
│ u32 ┆ u32     ┆ str       ┆ u32   ┆ str     ┆ str             ┆ str                      │
╞═════╪═════════╪═══════════╪═══════╪═════════╪═════════════════╪══════════════════════════╡
│ 0   ┆ 0       ┆ null      ┆ 4     ┆ null    ┆ is_contained_in ┆                          │
│ 1   ┆ 3       ┆ right     ┆ 2     ┆ top     ┆ is_connected_to ┆ Node2Node                │
│ 2   ┆ 1       ┆ null      ┆ 5     ┆ null    ┆ is_contained_in ┆                          │
│ 3   ┆ 3       ┆ bottom    ┆ 1     ┆ bottom  ┆ is_connected_to ┆ Circular Relation In     │
│ 4   ┆ 0       ┆ null      ┆ 6     ┆ null    ┆ is_contained_in ┆                          │
│ 5   ┆ 0       ┆ null      ┆ 1     ┆ null    ┆ references      ┆ null                     │
│ 6   ┆ 1       ┆ top       ┆ 3     ┆ top     ┆ is_connected_to ┆ Circular Relation Out    │
│ 7   ┆ 3       ┆ null      ┆ 1     ┆ null    ┆ references      ┆ null                     │
│ 8   ┆ 7       ┆ null      ┆ 0     ┆ null    ┆ references      ┆ null                     │
│ 9   ┆ 3       ┆ null      ┆ 2     ┆ null    ┆ references      ┆ null                     │
│ 10  ┆ 3       ┆ null      ┆ 5     ┆ null    ┆ is_contained_in ┆                          │
│ 11  ┆ 1       ┆ null      ┆ 1     ┆ null    ┆ references      ┆ null                     │
│ 12  ┆ 3       ┆ null      ┆ 4     ┆ null    ┆ is_contained_in ┆                          │
│ 13  ┆ 2       ┆ null      ┆ 0     ┆ null    ┆ references      ┆ null                     │
│ 14  ┆ 2       ┆ null      ┆ 1     ┆ null    ┆ references      ┆ null                     │
│ 15  ┆ 2       ┆ null      ┆ 3     ┆ null    ┆ references      ┆ note_1                   │
│ 16  ┆ 1       ┆ bottom    ┆ 4     ┆ left    ┆ is_connected_to ┆ Is not included in Group │
│ 17  ┆ 7       ┆ null      ┆ 5     ┆ null    ┆ is_contained_in ┆                          │
│ 18  ┆ 2       ┆ null      ┆ 6     ┆ null    ┆ is_contained_in ┆                          │
│ 19  ┆ 1       ┆ left      ┆ 7     ┆ right   ┆ is_connected_to ┆ File2Text                │
│ 20  ┆ 5       ┆ top       ┆ 4     ┆ top     ┆ is_connected_to ┆ Group2Group              │
│ 21  ┆ 2       ┆ null      ┆ 4     ┆ null    ┆ is_contained_in ┆                          │
└─────┴─────────┴───────────┴───────┴─────────┴─────────────────┴──────────────────────────┘

In [7]:
ds.nodes

shape: (10, 4)
┌─────┬───────┬─────────────────────────────────┬──────────────────────────────────┐
│ id  ┆ type  ┆ content                         ┆ loc                              │
│ --- ┆ ---   ┆ ---                             ┆ ---                              │
│ u32 ┆ str   ┆ str                             ┆ list[array[i128, (2, 2)]]        │
╞═════╪═══════╪═════════════════════════════════╪══════════════════════════════════╡
│ 0   ┆ note  ┆ note_2                          ┆ [[[-462, -62], [132, 532]]]      │
│     ┆       ┆                                 ┆                                  │
│     ┆       ┆ [[note_1]]                      ┆                                  │
│ 1   ┆ note  ┆ note_1                          ┆ [[[-1480, -1080], [-840, -440]]] │
│     ┆       ┆                                 ┆                                  │
│     ┆       ┆                                 ┆                                  │
│ 2   ┆ note  ┆ note_0                          ┆ [[[60, 460], [0, 400]]]          │
│     ┆       ┆                                 ┆                                  │
│     ┆       ┆ [[note_2]]                      ┆                                  │
│     ┆       ┆ [[note_1]]                      ┆                                  │
│     ┆       ┆ [[fold1/fold1-1/note_1|note_1]] ┆                                  │
│     ┆       ┆ [[fold1/note_1|note_1]]         ┆                                  │
│     ┆       ┆ [[note_1]]                      ┆                                  │
│     ┆       ┆ [[fold2/note_1#H1#H1|note_1]]   ┆                                  │
│     ┆       ┆                                 ┆                                  │
│     ┆       ┆ [[note_1]]                      ┆                                  │
│ 3   ┆ note  ┆ note_1                          ┆ [[[-462, -62], [-840, -440]]]    │
│     ┆       ┆                                 ┆                                  │
│     ┆       ┆ [[note_1]]                      ┆                                  │
│     ┆       ┆ [[note_0]]                      ┆                                  │
│ 4   ┆ group ┆ Group1                          ┆ [[[-600, 640], [-1160, 680]]]    │
│ 5   ┆ group ┆ Group0                          ┆ [[[-1943, 60], [-907, -360]]]    │
│ 6   ┆ group ┆ Group3                          ┆ [[[-520, 520], [-120, 600]]]     │
│ 7   ┆ note  ┆ Plain text node                 ┆ [[[-1900, -1680], [-584, -440]]] │
│     ┆       ┆ [[note_2]]                      ┆                                  │
│     ┆       ┆ [[fold1/note_2]]                ┆                                  │
│ 8   ┆ note  ┆ Haul note                       ┆ [[[-1805, -1400], [-260, 420]]]  │
│ 9   ┆ note  ┆ Spatially included note         ┆ [[[-1790, -1480], [-190, 280]]]  │
└─────┴───────┴─────────────────────────────────┴──────────────────────────────────┘