In [1]:
import json
from oltk.dataset.canvas_dataset import CanvasDataset

In [2]:
with open('/Users/igorkharchikov/Codes/ObsidianLTK/examples/data/TestObscureVault/Test.canvas', 'r', encoding='utf-8') as file:
    data = json.load(file)

In [3]:
data

{'nodes': [{'id': '4d1d094ad412ba9e',
   'type': 'group',
   'x': -600,
   'y': -1160,
   'width': 1240,
   'height': 1840,
   'label': 'Group1'},
  {'id': '12214884eeb600c2',
   'type': 'group',
   'x': -1943,
   'y': -907,
   'width': 2003,
   'height': 547,
   'label': 'Group0'},
  {'id': '962c9099317e6a70',
   'type': 'group',
   'x': -520,
   'y': -120,
   'width': 1040,
   'height': 720,
   'label': 'Group3'},
  {'id': '256f9c2f1de72edf',
   'type': 'file',
   'file': 'fold1/note_2.md',
   'x': -462,
   'y': 132,
   'width': 400,
   'height': 400},
  {'id': '28cd5c4111efdac1',
   'type': 'file',
   'file': 'note_0.md',
   'x': 60,
   'y': 0,
   'width': 400,
   'height': 400},
  {'id': '8c5ed30f4bae2c21',
   'type': 'file',
   'file': 'note_1.md',
   'x': -1480,
   'y': -840,
   'width': 400,
   'height': 400},
  {'id': '0cac5a1aec3d9c02',
   'type': 'file',
   'file': 'fold1/fold1-1/note_1.md',
   'x': -462,
   'y': -840,
   'width': 400,
   'height': 400},
  {'id': '5f6443636fe97e55',
   'type': 'text',
   'text': 'Plain text node\n[[note_2]]\n[[fold1/note_2]]',
   'x': -1900,
   'y': -584,
   'width': 220,
   'height': 144},
  {'id': '9a8778f0304076fc',
   'type': 'text',
   'text': 'Haul note',
   'x': -1805,
   'y': -260,
   'width': 405,
   'height': 680},
  {'id': 'b192f90932f8fb69',
   'type': 'text',
   'text': 'Spatially included note',
   'x': -1790,
   'y': -190,
   'width': 310,
   'height': 470}],
 'edges': [{'id': 'edfc7bcd3a33fd0e',
   'fromNode': '8c5ed30f4bae2c21',
   'fromSide': 'bottom',
   'toNode': '4d1d094ad412ba9e',
   'toSide': 'left',
   'label': 'Is not included in Group'},
  {'id': '4c4b957f5fd8be61',
   'fromNode': '0cac5a1aec3d9c02',
   'fromSide': 'right',
   'toNode': '28cd5c4111efdac1',
   'toSide': 'top',
   'label': 'Node2Node'},
  {'id': 'b61e0bc322a85d89',
   'fromNode': '12214884eeb600c2',
   'fromSide': 'top',
   'toNode': '4d1d094ad412ba9e',
   'toSide': 'top',
   'label': 'Group2Group'},
  {'id': '28a2ad65b92d23ae',
   'fromNode': '8c5ed30f4bae2c21',
   'fromSide': 'top',
   'toNode': '0cac5a1aec3d9c02',
   'toSide': 'top',
   'label': 'Circular Relation Out'},
  {'id': 'e0b0209201318330',
   'fromNode': '0cac5a1aec3d9c02',
   'fromSide': 'bottom',
   'toNode': '8c5ed30f4bae2c21',
   'toSide': 'bottom',
   'label': 'Circular Relation In'},
  {'id': 'f86aaf0eb3110093',
   'fromNode': '8c5ed30f4bae2c21',
   'fromSide': 'left',
   'toNode': '5f6443636fe97e55',
   'toSide': 'right',
   'label': 'File2Text'}]}

In [4]:
import polars as pl
pl.Config.set_fmt_str_lengths(256)
pl.Config.set_tbl_rows(32)

polars.config.Config

In [5]:
ds = CanvasDataset(root="./data/TestObscureVault", path="./data/TestObscureVault/Test.canvas")

In [6]:
ds.edges

shape: (22, 7)
┌─────┬─────────┬───────────┬───────┬─────────┬─────────────────┬──────────────────────────┐
│ id  ┆ from_id ┆ from_side ┆ to_id ┆ to_side ┆ type            ┆ label                    │
│ --- ┆ ---     ┆ ---       ┆ ---   ┆ ---     ┆ ---             ┆ ---                      │
│ u32 ┆ u32     ┆ str       ┆ u32   ┆ str     ┆ str             ┆ str                      │
╞═════╪═════════╪═══════════╪═══════╪═════════╪═════════════════╪══════════════════════════╡
│ 0   ┆ 1       ┆ null      ┆ 4     ┆ null    ┆ is_contained_in ┆                          │
│ 1   ┆ 2       ┆ null      ┆ 0     ┆ null    ┆ references      ┆ null                     │
│ 2   ┆ 0       ┆ left      ┆ 7     ┆ right   ┆ is_connected_to ┆ File2Text                │
│ 3   ┆ 3       ┆ null      ┆ 6     ┆ null    ┆ is_contained_in ┆                          │
│ 4   ┆ 1       ┆ bottom    ┆ 0     ┆ bottom  ┆ is_connected_to ┆ Circular Relation In     │
│ 5   ┆ 0       ┆ bottom    ┆ 4     ┆ left    ┆ is_connected_to ┆ Is not included in Group │
│ 6   ┆ 0       ┆ null      ┆ 5     ┆ null    ┆ is_contained_in ┆                          │
│ 7   ┆ 1       ┆ null      ┆ 0     ┆ null    ┆ references      ┆ null                     │
│ 8   ┆ 0       ┆ top       ┆ 1     ┆ top     ┆ is_connected_to ┆ Circular Relation Out    │
│ 9   ┆ 2       ┆ null      ┆ 6     ┆ null    ┆ is_contained_in ┆                          │
│ 10  ┆ 0       ┆ null      ┆ 0     ┆ null    ┆ references      ┆ null                     │
│ 11  ┆ 1       ┆ right     ┆ 3     ┆ top     ┆ is_connected_to ┆ Node2Node                │
│ 12  ┆ 3       ┆ null      ┆ 2     ┆ null    ┆ references      ┆ null                     │
│ 13  ┆ 3       ┆ null      ┆ 1     ┆ null    ┆ references      ┆ note_1                   │
│ 14  ┆ 1       ┆ null      ┆ 5     ┆ null    ┆ is_contained_in ┆                          │
│ 15  ┆ 3       ┆ null      ┆ 0     ┆ null    ┆ references      ┆ null                     │
│ 16  ┆ 3       ┆ null      ┆ 4     ┆ null    ┆ is_contained_in ┆                          │
│ 17  ┆ 7       ┆ null      ┆ 5     ┆ null    ┆ is_contained_in ┆                          │
│ 18  ┆ 7       ┆ null      ┆ 2     ┆ null    ┆ references      ┆ null                     │
│ 19  ┆ 5       ┆ top       ┆ 4     ┆ top     ┆ is_connected_to ┆ Group2Group              │
│ 20  ┆ 2       ┆ null      ┆ 4     ┆ null    ┆ is_contained_in ┆                          │
│ 21  ┆ 1       ┆ null      ┆ 3     ┆ null    ┆ references      ┆ null                     │
└─────┴─────────┴───────────┴───────┴─────────┴─────────────────┴──────────────────────────┘

In [7]:
ds.nodes

shape: (10, 4)
┌─────┬───────┬─────────────────────────────────┬──────────────────────────────────┐
│ id  ┆ type  ┆ content                         ┆ loc                              │
│ --- ┆ ---   ┆ ---                             ┆ ---                              │
│ u32 ┆ str   ┆ str                             ┆ list[array[i128, (2, 2)]]        │
╞═════╪═══════╪═════════════════════════════════╪══════════════════════════════════╡
│ 0   ┆ note  ┆                                 ┆ [[[-1480, -1080], [-840, -440]]] │
│ 1   ┆ note  ┆ [[note_1]]                      ┆ [[[-462, -62], [-840, -440]]]    │
│     ┆       ┆ [[note_0]]                      ┆                                  │
│ 2   ┆ note  ┆ [[note_1]]                      ┆ [[[-462, -62], [132, 532]]]      │
│ 3   ┆ note  ┆ [[note_2]]                      ┆ [[[60, 460], [0, 400]]]          │
│     ┆       ┆ [[note_1]]                      ┆                                  │
│     ┆       ┆ [[fold1/fold1-1/note_1|note_1]] ┆                                  │
│     ┆       ┆ [[fold1/note_1|note_1]]         ┆                                  │
│     ┆       ┆ [[note_1]]                      ┆                                  │
│     ┆       ┆ [[fold2/note_1#H1#H1|note_1]]   ┆                                  │
│     ┆       ┆                                 ┆                                  │
│     ┆       ┆ [[note_1]]                      ┆                                  │
│ 4   ┆ group ┆ Group1                          ┆ [[[-600, 640], [-1160, 680]]]    │
│ 5   ┆ group ┆ Group0                          ┆ [[[-1943, 60], [-907, -360]]]    │
│ 6   ┆ group ┆ Group3                          ┆ [[[-520, 520], [-120, 600]]]     │
│ 7   ┆ note  ┆ Plain text node                 ┆ [[[-1900, -1680], [-584, -440]]] │
│     ┆       ┆ [[note_2]]                      ┆                                  │
│     ┆       ┆ [[fold1/note_2]]                ┆                                  │
│ 8   ┆ note  ┆ Haul note                       ┆ [[[-1805, -1400], [-260, 420]]]  │
│ 9   ┆ note  ┆ Spatially included note         ┆ [[[-1790, -1480], [-190, 280]]]  │
└─────┴───────┴─────────────────────────────────┴──────────────────────────────────┘